services:
  mysql:
    image: mysql:8.4
    container_name: splim-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${MYSQL_HOST_PORT}:${MYSQL_CONTAINER_PORT}"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: splim-app
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_URL: ${DB_URL_DOCKER}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      JWT_SECRET: ${JWT_SECRET}
      STEAM_API_KEY: ${STEAM_API_KEY}
      STEAM_API_BASE_URL: ${STEAM_API_BASE_URL}
    ports:
      - "${APP_HOST_PORT}:8080"
    restart: unless-stopped

volumes:
  mysql_data: